trigger updateSat Apr 29 10:29:07 CST 2023

diff --git a/aria2/files/aria2.init b/aria2/files/aria2.init
--- a/aria2/files/aria2.init
+++ b/aria2/files/aria2.init
@@ -176,12 +176,17 @@ aria2_start() {
 		return 1
 	}
 
-	if ($config_dir != "/usr/share/aria2"); then
-		cp -rf /usr/share/aria2/* $config_dir
-	fi
+	# if config_dir the same with script_dir not copy it.
+	[ "$config_dir" = "/usr/share/aria2" ] || cp -rf /usr/share/aria2/* $config_dir
 
-	_create_file "$session_file" "$config_file" "$config_file_tmp" || {
-		_err "Can't create files: $session_file, $config_file, $config_file_tmp"
+	# create session file if not exist.
+	[ -f $session_file ] || _create_file $session_file || {
+		_err "Can't create files: $session_file"
+		return 1
+	}
+
+	_create_file "$config_file" "$config_file_tmp" || {
+		_err "Can't create files: $config_file, $config_file_tmp"
 		return 1
 	}
 
@@ -317,6 +322,27 @@ aria2_start() {
 	config_list_foreach "$section" "header" append_header
 	config_list_foreach "$section" "extra_settings" append_setting
 
+	# fix filename errors
+	append_setting "content-disposition-default-utf8=true"
+
+	# retry at more event
+	append_setting "retry-on-400=true"
+	append_setting "retry-on-403=true"
+	append_setting "retry-on-406=true"
+
+	# auto rename file
+	append_setting "auto-file-renaming=true"
+
+	# allow piece length change
+	append_setting "allow-piece-length-change=true"
+
+	# let retry wait 10 secend
+	append_setting "retry-wait=10"
+
+	# default add auto clean when remove file
+	append_setting "on-download-complete=$config_dir/clean.sh"
+	append_setting "on-download-stop=$config_dir/delete.sh"
+
 	sed '/^$/d' "$config_file_tmp" >"$config_file"
 	rm -f "$config_file_tmp"
 
@@ -351,7 +377,7 @@ aria2_start() {
 	procd_add_jail_mount "$ca_certificate" "$certificate" "$rpc_certificate" "$rpc_private_key"
 	procd_add_jail_mount_rw "$dir" "$config_dir" "$log"
 	chmod -R +x $config_dir
-	sh $config_dir/tracker.sh $config_file > /dev/null 2>&1 &
+	sh $config_dir/tracker.sh $config_file >/dev/null 2>&1
 	procd_close_instance
 	sed -i '/tracker.sh/d' /etc/crontabs/root >/dev/null 2>&1
 	echo "* */6 * * * $config_dir/tracker.sh $config_file RPC" >> /etc/crontabs/root
